AirlineMVC3/Models/FlightViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using AirlineMVC3.BL;

namespace AirlineMVC3.Models
{
    public class FlightViewModel
    {
        [Display(Name ="Flight Number")]
        public int FlightNumber { get; set; }

        [Display(Name="Flight Type")]
        public FlightType FlightType { get; set; }

        [Display(Name ="Date Time")]
        public DateTime FLDate { get; set; }

        [Display(Name ="Port")]
        public string Port { get; set; }

        [Display(Name ="Terminal")]
        public int Terminal { get; set; }

        [Display(Name ="Company")]
        public string Company { get; set; }

        [Display(Name="Business Price")]
        public decimal BusinessPrice { get; set; }

        [Display(Name="Econom Price")]
        public decimal EconomPrice { get; set; }

        [Display(Name="Flight Status")]
        public FlightStatus FlightStatus { get; set; }

        public FlightViewModel()
        {

        }

        public FlightViewModel(int fltNum, FlightType fltType, DateTime date, string port, int terminal, string company, decimal bisPrice, decimal ecPrice, FlightStatus status)
        {
            this.FlightNumber = fltNum;
            this.FlightType = fltType;
            this.FLDate = date;
            this.Terminal = terminal;
            this.Port = port;
            this.Company = company;
            this.BusinessPrice = bisPrice;
            this.EconomPrice = ecPrice;
            this.FlightStatus = status;
        }
    }
}

AirlineMVC3/Controllers/FlightsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using AirlineMVC3.BL;
using AirlineMVC3.Models;

namespace AirlineMVC3.Controllers
{
    public class FlightsController : Controller
    {
        private IFlightService flightService;
        private IPassengerService passengerService;

        public FlightsController()
        {
            this.flightService = new FlightService();
            this.passengerService = new PassengerService();
        }
        // GET: Flights
        public ActionResult Index(string searchBy, string search, string searchOutputType)
        {
            IServiceResult<IEnumerable<FlightBLModel>> serviceResult;

            Func<FlightBLModel, bool> searchOutputPredicate = flight
                => true;

            if (search == string.Empty) searchBy = string.Empty;

            switch (searchBy)
            {
                case "FlightNumber":
                    serviceResult = this.flightService.GetFlightByNumber(search);
                    break;
                case "Port":
                    serviceResult = this.flightService.GetFlightsByPort(search);
                    break;
                default:
                    serviceResult = this.flightService.GetAll();
                    break;
            }

            switch (searchOutputType)
            {
                case "Departure":
                    searchOutputPredicate = flight
                        => flight.FlightType == FlightType.Departure;
                    break;
                case "Arrival":
                    searchOutputPredicate = flight
                        => flight.FlightType == FlightType.Arrival;
                    break;
                default:
                    break;
            }

            if (!serviceResult.IsSuccess)
            {
                return Redirect("Errors/Error");
            }

            var flightViewList = serviceResult.Data
                .Where(searchOutputPredicate)
                .Select(flt => FlightsController.convertToVM(flt))
                .ToList();

            return View(flightViewList);
        }

        public ActionResult Edit(int? id)
        {

            if (!id.HasValue)
            {
                return Redirect("Errors/PageDoesNotExist");
            }

            
            var flightServiceResp = this.flightService.Get(id.Value);

            if (!flightServiceResp.IsSuccess)
            {
                return Redirect("Errors/Error");
            }

            var fltView = FlightsController.convertToVM(flightServiceResp.Data);

            return View(fltView);           
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(FlightViewModel fltView)
        {
            if (!ModelState.IsValid)
            {
                return View(fltView);
            }

            var serviceResp = this.flightService.Update(FlightsController.convertToBL(fltView));

            if (!serviceResp.IsSuccess)
            {
                return Redirect("Errors/Error");
            }

            return RedirectToAction("Index");
        }

        public ActionResult Details(int? id)
        {
            if (!id.HasValue)
            {
                return Redirect("Errors/Error");
            }

            var serviceResponce = this.flightService.Get(id.Value);

            if (!serviceResponce.IsSuccess)
            {
                return Redirect("Errors/Error"); 
            }

            var passServiceResponce = this.passengerService.GetAll();

            if (!passServiceResponce.IsSuccess)
            {
                ViewData["passengers"] = null;
            } else
            {
                ViewData["passengers"] = passServiceResponce.Data
                    .Where(pass => pass.FlightNumber == id)
                    .Select(pass => PassengersController.convertToVM(pass))
                    .ToList();
            }

            return View(FlightsController.convertToVM(serviceResponce.Data));
        }

        public ActionResult Create()
        {
            return View(new FlightViewModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Exclude = "FlightNumber")] FlightViewModel flt)
        {
            if (!ModelState.IsValid)
            {
                return Redirect("../Errors/Error");
            }

            var serviceResponce = flightService.Create(convertToBL(flt));

            if (!serviceResponce.IsSuccess)
            {
                return View();
            }

            return RedirectToAction("Index");
        }

        public ActionResult Delete(int? id)
        {
            if (!id.HasValue)
            {
                return Redirect("../Errors/Error");
            }

            var serviceResponce = this.flightService.Get(id.Value);

            if (!serviceResponce.IsSuccess)
            {
                return Redirect("../Errors/PageDoesNotExist");
            }

            ViewBag.ErrorMessage = null;

            var passServiceResponce = this.passengerService.GetAll();

            if (!passServiceResponce.IsSuccess)
            {
                ViewBag.PassengerList = null;
            }
            else
            {
                ViewBag.PassengerList = passServiceResponce.Data
                    .Where(pass => pass.FlightNumber == id)
                    .Select(pass => PassengersController.convertToVM(pass))
                    .ToList();
            }

            var flight = FlightsController.convertToVM(serviceResponce.Data);

            return View(flight);


        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(FlightViewModel flight)
        {
            var serviceResponce = this.flightService.Delete(flight.FlightNumber);

            if (!serviceResponce.IsSuccess)
            {
                var passServiceResponce = this.passengerService.GetAll();

                if (!passServiceResponce.IsSuccess)
                {
                    ViewBag.PassengerList = null;
                }
                else
                {
                    ViewBag.PassengerList = passServiceResponce.Data
                        .Where(pass => pass.FlightNumber == flight.FlightNumber)
                        .Select(pass => PassengersController.convertToVM(pass))
                        .ToList();
                }

                ViewBag.ErrorMessage = "Error: Can't delete flight with passengers. Delete passengers from the flight first";

                return View(flight);
            }

            return RedirectToAction("Index");
        }


        public static FlightViewModel convertToVM(FlightBLModel flt)
        {
            return new FlightViewModel(
                flt.FlightNumber,
                flt.FlightType,
                flt.FLDate,
                flt.Port,
                flt.Terminal,
                flt.Company,
                flt.BusinessPrice,
                flt.EconomPrice,
                flt.FlightStatus);
        }

        public static FlightBLModel convertToBL(FlightViewModel flt)
        {
            return new FlightBLModel(
                flt.FlightNumber,
                flt.FlightType,
                flt.FLDate,
                flt.Port,
                flt.Terminal,
                flt.Company,
                flt.BusinessPrice,
                flt.EconomPrice,
                flt.FlightStatus);
        }
    }
}

AirlineMVC3/Views/Flights/Create.cshtml
@model AirlineMVC3.Models.FlightViewModel
@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    Html.RenderPartial("PartFlightProp");

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

AirlineMVC3/Views/Flights/Delete.cshtml
@model AirlineMVC3.Models.FlightViewModel

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

@if (ViewBag.ErrorMessage != null)
{
    <h2 class="text-danger">@ViewBag.ErrorMessage</h2>
}

<h3>Are you sure you want to delete this?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FlightNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FlightNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FLDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FLDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Port)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Port)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Terminal)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Terminal)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Company)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Company)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BusinessPrice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BusinessPrice)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EconomPrice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EconomPrice)
        </dd>

    </dl>

    <div>
        @{Html.RenderPartial("../Passengers/PartPassDetails", ViewBag.PassengerList as IEnumerable<AirlineMVC3.Models.PassengerViewModel>);}
    </div>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.FlightNumber);
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

AirlineMVC3/Views/Flights/Details.cshtml
@model AirlineMVC3.Models.FlightViewModel

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>FlightViewModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FlightNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FlightNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FlightType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FlightType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FLDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FLDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Port)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Port)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Terminal)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Terminal)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Company)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Company)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BusinessPrice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BusinessPrice)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EconomPrice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EconomPrice)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FlightStatus)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FlightStatus)
        </dd>

    </dl>
</div>

<div>
    @{Html.RenderPartial("../Passengers/PartPassDetails", ViewData["passengers"]);}
</div>

<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.FlightNumber}) |
    @Html.ActionLink("Back to List", "Index")
</p>

AirlineMVC3/Views/Flights/Edit.cshtml
@model AirlineMVC3.Models.FlightViewModel

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

            Html.RenderPartial("PartFlightProp");

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

AirlineMVC3/Views/Flights/Index.cshtml
@model IEnumerable<AirlineMVC3.Models.FlightViewModel>

@{
    ViewBag.Title = "Index";
}

<h2>Flights</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

<p>
    @using (Html.BeginForm("Index", "Flights", FormMethod.Get))
    {
    <div class="search-control">
        <b>Search Output</b>
        @Html.RadioButton("searchOutputType", "All", true) <text>All Types</text>
        @Html.RadioButton("searchOutputType", "Arrival") <text>Arrival</text>
        @Html.RadioButton("searchOutputType", "Departure") <text>Departure</text>
        <br />
    </div>

    <div class="search-control">
        <b>Search By</b>
        @Html.RadioButton("searchBy", "FlightNumber", true) <text>Flight Number</text>
        @Html.RadioButton("searchBy", "Port") <text>Port</text>
        <br />
        @Html.TextBox("search") <input value="search" type="submit" />
    </div>

    }
</p>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FlightNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FlightType);
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FLDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Port)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Terminal)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Company)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BusinessPrice)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EconomPrice)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FlightStatus);
        </th>
        <th></th>
    </tr>
    @if (Model.Count() == 0)
    {
        <tr>
            <td>
                <b>No flights found by this request</b>
            </td>
        </tr>
    }
    else
    {
        foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.FlightNumber)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FlightType)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FLDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Port)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Terminal)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Company)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.BusinessPrice)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EconomPrice)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FlightStatus)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.FlightNumber }) |
                    @Html.ActionLink("Details", "Details", new { id = item.FlightNumber }) |
                    @if (!Request.RawUrl.Contains("Passengers"))
                    {
                        @Html.ActionLink("Delete", "Delete", new { id = item.FlightNumber })
                    }
                </td>
            </tr>
        }

    }

</table>

AirlineMVC3/Views/Flights/PartFlightProp.cshtml
@model AirlineMVC3.Models.FlightViewModel

<div class="form-horizontal">

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        <div class="col-md-10">
            @Html.HiddenFor(model => model.FlightNumber, new { htmlAttributes = new { @class = "form-control-static" } })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.FlightType, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EnumDropDownListFor(model => model.FlightType, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.FlightType, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.FLDate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.FLDate, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.FLDate, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Port, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Port, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Port, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Terminal, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Terminal, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Terminal, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Company, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Company, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Company, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.BusinessPrice, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.BusinessPrice, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.BusinessPrice, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.EconomPrice, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.EconomPrice, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.EconomPrice, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.FlightStatus, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EnumDropDownListFor(model => model.FlightStatus, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.FlightStatus, "", new { @class = "text-danger" })
        </div>
    </div>
</div>