AirlineMVC3/Models/PassengerViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;
using AirlineMVC3.BL;

namespace AirlineMVC3.Models
{
    public class PassengerViewModel
    {
        [Display(Name="Passenger Id")]
        public int PassengerId { get; set; }

        [Display(Name="Passport Code")]
        public string Passport { get; set; }

        [Display(Name="First Name")]
        public string FirstName { get; set; }

        [Display(Name="Last Name")]
        public string LastName { get; set; }

        [Display(Name="Nationality")]
        public string Nationality { get; set; }

        [Display(Name="Flight Number")]
        public int? FlightNumber { get; set; }

        [Display(Name="Birth Date")]
        public DateTime BirthDate { get; set; }

        [Display(Name="Gender")]
        public Gender Gender { get; set; }

        [Display(Name ="Price Class")]
        public PriceClass? Class { get; set; }

        public PassengerViewModel()
        {

        }

        public PassengerViewModel(int passId, string passport, string firstName, string lastName, string nationality, int? flightNumber, DateTime birtDate, Gender gender, PriceClass? prClass)
        {
            this.PassengerId = passId;
            this.Passport = passport;
            this.FirstName = firstName;
            this.LastName = lastName;
            this.Nationality = nationality;
            this.FlightNumber = flightNumber;
            this.BirthDate = birtDate;
            this.Gender = gender;
            this.Class = prClass;
        }

    }
}

AirlineMVC3/Controllers/PassengersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AirlineMVC3.BL;
using AirlineMVC3.Models;

namespace AirlineMVC3.Controllers
{
    public class PassengersController : Controller
    {
        IFlightService flightService;
        IPassengerService passengerService;
        SelectList priceClassOptions;

        public PassengersController()
        {
            this.flightService = new FlightService();
            this.passengerService = new PassengerService();
            this.priceClassOptions = new SelectList(new List<PriceClass?> { null, PriceClass.Business, PriceClass.Econom });
        }

        // GET: Passengers
        [ActionName("IndexInitial")]
        public ActionResult Index()
        {
            var passServiceResponce = this.passengerService.GetAll();

            if (!passServiceResponce.IsSuccess)
            {
                return Redirect("../Errors/Error");
            }

            var passengers = passServiceResponce.Data
                .Select(pass => PassengersController.convertToVM(pass))
                .ToList();


            return View(passengers);
        }

        public ActionResult Index(string search, string searchBy)
        {
            IServiceResult<IEnumerable<PassengerBLModel>> passServiceResponce;

            if (search == string.Empty) searchBy = string.Empty;

            switch (searchBy)
            {
                case "FirstName":
                    passServiceResponce = passengerService.GetPassengerByFirstName(search);
                    break;
                case "LastName":
                    passServiceResponce = passengerService.GetPassengerByLastName(search);
                    break;
                case "Passport":
                    passServiceResponce = passengerService.GetPassengerByPassport(search);
                    break;
                case "FlightNumber":
                    passServiceResponce = passengerService.GetPassengersByFlightNumber(search);
                    break;
                default:
                    passServiceResponce = this.passengerService.GetAll();
                    break;
            }

            if (!passServiceResponce.IsSuccess)
            {
                return Redirect("../Errors/Errors");
            }

            var pasengers = passServiceResponce.Data
                .Select(pass => PassengersController.convertToVM(pass))
                .ToList();

            return View(pasengers);
        }

        public ActionResult Details(int? id)
        {
            if (!id.HasValue)
            {
                return Redirect("../Errors/Error");
            }

            var passServiceResponce = this.passengerService.Get(id.Value);

            if (!passServiceResponce.IsSuccess)
            {
                return Redirect("../Errors/PageDoesNotExist");
            }

            var passenger = PassengersController.convertToVM(passServiceResponce.Data);

            ViewBag.CurrentFlight = new List<FlightViewModel>();

            if (passenger.FlightNumber.HasValue)
            {
                var flightServiceResponce = this.flightService.Get(passServiceResponce.Data.FlightNumber.Value);

                if (flightServiceResponce.IsSuccess)
                {
                    ViewBag.CurrentFlight.Add(FlightsController.convertToVM(flightServiceResponce.Data));
                }

            }

            return View(passenger);
        }

        public ActionResult Edit(int? id)
        {
            if (!id.HasValue || id == null)
            {
                return Redirect("../Errors/PageDoesNotExists");
            }

            var passServiceResponce = this.passengerService.Get(id.Value);
          
            var passenger = PassengersController.convertToVM(passServiceResponce.Data);

            ViewBag.FlightNums = this.getFlightNums();
            ViewBag.ClassList = priceClassOptions;

            return View(passenger);

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(PassengerViewModel pass)
        {
            if((pass.FlightNumber == null && pass.Class != null))
            {
                ModelState.AddModelError("Class", "Class shoul be null if flight number is null");
            }

            if((pass.FlightNumber != null && pass.Class == null))
            {
                ModelState.AddModelError("Class", "Class shouldn't be null if flight number in not null");
            }

            if (!ModelState.IsValid)
            {
                ViewBag.FlightNums = this.getFlightNums();
                ViewBag.ClassList = this.priceClassOptions;
                return View(pass);
            }

            var serviceResponce = this.passengerService.Update(PassengersController.convertToBL(pass));

            if (!serviceResponce.IsSuccess)
            {
                return Redirect("../Errors/Error");
            }

            return RedirectToAction("Index");
        }

        public ActionResult Create()
        {
            ViewBag.FlightNums = this.getFlightNums();
            ViewBag.ClassList = this.priceClassOptions;

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Exclude = "PassengerId")] PassengerViewModel pass)
        {

            if (!ModelState.IsValid)
            {
                ViewBag.FlightNums = this.getFlightNums();
                ViewBag.ClassList = this.priceClassOptions;
                return View(pass);
            }

            var passServiceResponce = this.passengerService.Create(PassengersController.convertToBL(pass));

            if (!passServiceResponce.IsSuccess)
            {
                return Redirect("../Errors/Error");
            }

            return RedirectToAction("Index");
        }
      
        public ActionResult Delete(int? id)
        {
            if (!id.HasValue)
            {
                return Redirect("../Errors/PageDoesNotExists");
            }

            var serviceResponce = this.passengerService.Get(id.Value);

            if (!serviceResponce.IsSuccess)
            {
                return Redirect("../Errors/Error");
            }

            var passenger = PassengersController.convertToVM(serviceResponce.Data);

            return View(passenger);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(PassengerViewModel pass)
        {
            this.passengerService.Delete(pass.PassengerId);

            return RedirectToAction("Index");
        }

        public static PassengerViewModel convertToVM(PassengerBLModel pass)
        {
            return new PassengerViewModel(pass.PassengerId,
                pass.Passport,
                pass.FirstName,
                pass.LastName,
                pass.Nationality,
                pass.FlightNumber,
                pass.BirthDate,
                pass.Gender,
                pass.Class);
        }

        public static PassengerBLModel convertToBL(PassengerViewModel pass)
        {
            return new PassengerBLModel(pass.PassengerId,
                pass.Passport,
                pass.FirstName,
                pass.LastName,
                pass.Nationality,
                pass.FlightNumber,
                pass.BirthDate,
                pass.Gender,
                pass.Class);
        }

        private SelectList getFlightNums()
        {
            var fltServiceResponce = this.flightService.GetAll();

            if (!fltServiceResponce.IsSuccess)
            {
                return new SelectList(new int?[] { });
            }
            else
            {
                return new SelectList(fltServiceResponce.Data
                    .Select(flt => (int?)flt.FlightNumber)
                    .ToArray()
                    .Prepend(null));
            }
        }
    }
}

AirlineMVC3/Views/Passengers/Create.cshtml
@model AirlineMVC3.Models.PassengerViewModel
@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken();

    Html.RenderPartial("PartPassProp");

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
    <p>
        @Html.ActionLink("Back to List", "Index");
    </p>

}

AirlineMVC3/Views/Passengers/Delete.cshtml
@model AirlineMVC3.Models.PassengerViewModel

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>PassengerViewModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.PassengerId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PassengerId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Passport)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Passport)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nationality)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nationality)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FlightNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FlightNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BirthDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BirthDate)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.PassengerId);
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

AirlineMVC3/Views/Passengers/Details.cshtml
@model AirlineMVC3.Models.PassengerViewModel

@{
    ViewBag.Title = $"Passenger: {Model.FirstName} {Model.LastName}";
}

<h2>Details</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.PassengerId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PassengerId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Passport)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Passport)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nationality)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nationality)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FlightNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FlightNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BirthDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BirthDate)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.PassengerId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

@{Html.RenderPartial("../Flights/Index", ViewBag.CurrentFlight as IEnumerable<AirlineMVC3.Models.FlightViewModel>);}

AirlineMVC3/Views/Passengers/Edit.cshtml
@model AirlineMVC3.Models.PassengerViewModel

@{
    ViewBag.Title = $"Editing passcode: {Model.Passport}";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

            Html.RenderPartial("PartPassProp");

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

AirlineMVC3/Views/Passengers/Index.cshtml
@model IEnumerable<AirlineMVC3.Models.PassengerViewModel>
@{
    ViewBag.Title = "Index";
}

<h2>Passenger List</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

<p>
    @using (Html.BeginForm("Index", "Passengers", FormMethod.Get))
    {
        <b>Search By</b>
        @Html.RadioButton("searchBy", "FirstName", true) <text>First Name</text>
        @Html.RadioButton("searchBy", "LastName") <text>Last Name</text>
        @Html.RadioButton("searchBy", "Passport") <text>Passport</text>
        @Html.RadioButton("searchBy", "FlightNumber") <text>Flight Number</text>
        <br/>
        @Html.TextBox("search") <input type="submit" value="Search" />
    }
</p>
@{Html.RenderPartial("PartPassDetails");}

AirlineMVC3/Views/Passengers/PartPassDetails.cshtml
@model IEnumerable<AirlineMVC3.Models.PassengerViewModel>

<h4>Passenger list:</h4>

<table class="table">
    <tr>
        <th>@Html.DisplayNameFor(model => model.PassengerId)</th>
        <th>@Html.DisplayNameFor(model => model.Passport)</th>
        <th>@Html.DisplayNameFor(model => model.FirstName)</th>
        <th>@Html.DisplayNameFor(model => model.LastName)</th>
        <th>@Html.DisplayNameFor(model => model.Nationality)</th>
        <th>@Html.DisplayNameFor(model => model.FlightNumber)</th>
        <th>@Html.DisplayNameFor(model => model.BirthDate)</th>
        <th>@Html.DisplayNameFor(model => model.Gender)</th>
        <th>@Html.DisplayNameFor(model => model.Class) </th>
    </tr>
    @if (Model.Count() == 0)
    {
        <tr>
            <td colspan="8"><b>No passenger found by your request</b></td>
        </tr>
    }
    else
    {
        foreach (var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(modelItem => item.PassengerId)</td>
                <td>@Html.DisplayFor(modelItem => item.Passport)</td>
                <td>@Html.DisplayFor(modelItem => item.FirstName)</td>
                <td>@Html.DisplayFor(modelItem => item.LastName)</td>
                <td>@Html.DisplayFor(modelItem => item.Nationality)</td>
                <td>@Html.DisplayFor(modelItem => item.FlightNumber)</td>
                <td>@Html.DisplayFor(modelItem => item.BirthDate)</td>
                <td>@Html.DisplayFor(modelItem => item.Gender)</td>
                <td>@Html.DisplayFor(modelItem => item.Class)</td>
                <td>
                    @Html.ActionLink("Details", "Details", "Passengers", new { id = item.PassengerId }, null) |
                    @Html.ActionLink("Edit", "Edit", "Passengers", new { id = item.PassengerId }, null) |
                    @{
                        if (Request.RawUrl.Contains("Passengers"))
                        {
                            @Html.ActionLink("Delete", "Delete", "Passengers", new { id = item.PassengerId }, null);
                        }
                    }

                </td>
            </tr>
        }
    }

</table>

AirlineMVC3/Views/Passengers/PartPassProp.cshtml
@model AirlineMVC3.Models.PassengerViewModel

<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        <div class="col-md-10">
            @Html.HiddenFor(model => model.PassengerId, new { htmlAttributes = new { @class = "form-control-static" } })
        </div>
    </div>


    @if (Request.RawUrl.Contains("Create"))
    {
        <div class="form-group">
            @Html.LabelFor(model => model.Passport, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Passport, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Passport, "", new { @class = "text-danger" })
            </div>
        </div>
    }
    else
    {
        <div class="form-group">
            <div class="col-md-10">
                @Html.HiddenFor(model => model.Passport, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>
    }


    <div class="form-group">
        @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Nationality, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Nationality, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Nationality, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.FlightNumber, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.FlightNumber, ViewBag.FlightNums as SelectList)
            @Html.ValidationMessageFor(model => model.FlightNumber, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.BirthDate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.BirthDate, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.BirthDate, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EnumDropDownListFor(model => model.Gender, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Class, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.Class, ViewBag.ClassList as SelectList, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Class, "", new { @class = "text-danger" })
        </div>
    </div>
</div>